// src/shared/constants/errors.js

/**
 * RESQID Error Code Registry
 * Machine-readable codes sent in API error responses.
 * Frontend uses these to show specific messages.
 *
 * Format: DOMAIN_PROBLEM
 */

export const ERROR_CODES = Object.freeze({
  // Auth
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Module / Plan
  MODULE_NOT_ALLOWED: 'MODULE_NOT_ALLOWED',
  NO_SUBSCRIPTION: 'NO_SUBSCRIPTION',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',

  // School
  SCHOOL_NOT_FOUND: 'SCHOOL_NOT_FOUND',
  SCHOOL_INACTIVE: 'SCHOOL_INACTIVE',

  // Student
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_ALREADY_EXISTS: 'STUDENT_ALREADY_EXISTS',

  // Card / Token
  CARD_NOT_FOUND: 'CARD_NOT_FOUND',
  CARD_INACTIVE: 'CARD_INACTIVE',
  CARD_REVOKED: 'CARD_REVOKED',
  CARD_UNREGISTERED: 'CARD_UNREGISTERED',
  CARD_INVALID: 'CARD_INVALID',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PHONE: 'INVALID_PHONE',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // File
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Rate limit / Security
  RATE_LIMITED: 'RATE_LIMITED',
  IP_BLOCKED: 'IP_BLOCKED',
  CSRF_INVALID: 'CSRF_INVALID',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
});
