// orchestrator/events/event.types.js — RESQID
// Central registry of all event types across the system.

export const EVENTS = Object.freeze({
  // ── Emergency ────────────────────────────────────────────────────────────
  EMERGENCY_ALERT_TRIGGERED: 'EMERGENCY_ALERT_TRIGGERED',
  EMERGENCY_ALERT_DELIVERED: 'EMERGENCY_ALERT_DELIVERED',
  EMERGENCY_ALERT_FAILED: 'EMERGENCY_ALERT_FAILED',
  EMERGENCY_ALERT_ESCALATED: 'EMERGENCY_ALERT_ESCALATED',

  // ── Crisis (Timetable emergencies) ───────────────────────────────────────
  CRISIS_TRIGGERED: 'CRISIS_TRIGGERED',
  CRISIS_RESOLVED: 'CRISIS_RESOLVED',
  CRISIS_FAILED: 'CRISIS_FAILED',
  TEACHER_ABSENT_DETECTED: 'TEACHER_ABSENT_DETECTED',
  ROOM_UNAVAILABLE_DETECTED: 'ROOM_UNAVAILABLE_DETECTED',
  SUBSTITUTION_CREATED: 'SUBSTITUTION_CREATED',
  SUBSTITUTION_APPROVED: 'SUBSTITUTION_APPROVED',
  SUBSTITUTION_REJECTED: 'SUBSTITUTION_REJECTED',
  MASS_LEAVE_DETECTED: 'MASS_LEAVE_DETECTED', // 🔧 ADDED
  WEATHER_EVENT_DETECTED: 'WEATHER_EVENT_DETECTED', // 🔧 ADDED

  // ── Timetable Generation ─────────────────────────────────────────────────
  TIMETABLE_GENERATE_STARTED: 'TIMETABLE_GENERATE_STARTED',
  TIMETABLE_GENERATE_PROGRESS: 'TIMETABLE_GENERATE_PROGRESS',
  TIMETABLE_GENERATE_COMPLETED: 'TIMETABLE_GENERATE_COMPLETED',
  TIMETABLE_GENERATE_FAILED: 'TIMETABLE_GENERATE_FAILED',
  TIMETABLE_GENERATE_CANCELLED: 'TIMETABLE_GENERATE_CANCELLED',

  // ── Timetable Validation ─────────────────────────────────────────────────
  TIMETABLE_VALIDATE_STARTED: 'TIMETABLE_VALIDATE_STARTED',
  TIMETABLE_VALIDATE_COMPLETED: 'TIMETABLE_VALIDATE_COMPLETED',
  TIMETABLE_VALIDATE_FAILED: 'TIMETABLE_VALIDATE_FAILED',

  // ── Timetable Swap/Reschedule ────────────────────────────────────────────
  TIMETABLE_SWAP_REQUESTED: 'TIMETABLE_SWAP_REQUESTED',
  TIMETABLE_SWAP_COMPLETED: 'TIMETABLE_SWAP_COMPLETED',
  TIMETABLE_SWAP_FAILED: 'TIMETABLE_SWAP_FAILED',

  // ── Bulk Upload ──────────────────────────────────────────────────────────
  BULK_UPLOAD_STARTED: 'BULK_UPLOAD_STARTED',
  BULK_UPLOAD_PROGRESS: 'BULK_UPLOAD_PROGRESS',
  BULK_UPLOAD_COMPLETED: 'BULK_UPLOAD_COMPLETED',
  BULK_UPLOAD_FAILED: 'BULK_UPLOAD_FAILED',

  // ── Teacher Wellness ─────────────────────────────────────────────────────
  TEACHER_WELLNESS_UPDATED: 'TEACHER_WELLNESS_UPDATED',
  TEACHER_BURNOUT_RISK_DETECTED: 'TEACHER_BURNOUT_RISK_DETECTED',
  TEACHER_ACCESSIBILITY_VIOLATION: 'TEACHER_ACCESSIBILITY_VIOLATION',
  TEACHER_LOAD_WARNING: 'TEACHER_LOAD_WARNING', // 🔧 ADDED

  // ── Notification ─────────────────────────────────────────────────────────
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_DELIVERED: 'NOTIFICATION_DELIVERED',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',

  // ── Order lifecycle ───────────────────────────────────────────────────────
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_ADVANCE_INVOICE_ISSUED: 'ORDER_ADVANCE_INVOICE_ISSUED',
  PARTIAL_INVOICE_GENERATED: 'PARTIAL_INVOICE_GENERATED',
  ORDER_ADVANCE_PAYMENT_RECEIVED: 'ORDER_ADVANCE_PAYMENT_RECEIVED',
  PARTIAL_PAYMENT_CONFIRMED: 'PARTIAL_PAYMENT_CONFIRMED',
  ORDER_TOKEN_GENERATION_STARTED: 'ORDER_TOKEN_GENERATION_STARTED',
  ORDER_TOKEN_GENERATION_COMPLETE: 'ORDER_TOKEN_GENERATION_COMPLETE',
  ORDER_CARD_DESIGN_STARTED: 'ORDER_CARD_DESIGN_STARTED',
  ORDER_CARD_DESIGN_COMPLETE: 'ORDER_CARD_DESIGN_COMPLETE',
  ORDER_PDF_GENERATED: 'ORDER_PDF_GENERATED',
  ORDER_SENT_TO_VENDOR: 'ORDER_SENT_TO_VENDOR',
  ORDER_PRINTING_STARTED: 'ORDER_PRINTING_STARTED',
  ORDER_PRINTING_COMPLETE: 'ORDER_PRINTING_COMPLETE',
  ORDER_READY_TO_SHIP: 'ORDER_READY_TO_SHIP',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_BALANCE_INVOICE_ISSUED: 'ORDER_BALANCE_INVOICE_ISSUED',
  ORDER_BALANCE_PAYMENT_RECEIVED: 'ORDER_BALANCE_PAYMENT_RECEIVED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  ORDER_ON_HOLD: 'ORDER_ON_HOLD',
  DESIGN_APPROVED: 'DESIGN_APPROVED',

  // ── Auth / User ───────────────────────────────────────────────────────────
  USER_OTP_REQUESTED: 'USER_OTP_REQUESTED',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_DEVICE_LOGIN_NEW: 'USER_DEVICE_LOGIN_NEW',
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',
  SCHOOL_USER_PASSWORD_RESET: 'SCHOOL_USER_PASSWORD_RESET',

  // ── School ────────────────────────────────────────────────────────────────
  SCHOOL_ONBOARDED: 'SCHOOL_ONBOARDED',
  SCHOOL_USER_ONBOARDED: 'SCHOOL_USER_ONBOARDED',
  SCHOOL_RENEWAL_DUE: 'SCHOOL_RENEWAL_DUE',
  SCHOOL_RENEWAL_COMPLETED: 'SCHOOL_RENEWAL_COMPLETED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',

  // ── Student ───────────────────────────────────────────────────────────────
  STUDENT_REGISTERED: 'STUDENT_REGISTERED',
  STUDENT_QR_SCANNED: 'STUDENT_QR_SCANNED',
  STUDENT_CARD_ACTIVATED: 'STUDENT_CARD_ACTIVATED',
  STUDENT_CARD_DEACTIVATED: 'STUDENT_CARD_DEACTIVATED',
  STUDENT_CARD_EXPIRING: 'STUDENT_CARD_EXPIRING',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',
  PROFILE_SETUP_REMINDER: 'PROFILE_SETUP_REMINDER',

  // ── Parent ────────────────────────────────────────────────────────────────
  PARENT_EMAIL_VERIFIED: 'PARENT_EMAIL_VERIFIED',
  PARENT_REGISTERED: 'PARENT_REGISTERED',
  PARENT_CARD_LINKED: 'PARENT_CARD_LINKED',
  PARENT_CARD_LOCKED: 'PARENT_CARD_LOCKED',
  PARENT_CARD_REPLACE_REQUESTED: 'PARENT_CARD_REPLACE_REQUESTED',
  PARENT_ACCOUNT_DELETED: 'PARENT_ACCOUNT_DELETED',
  PARENT_PHONE_CHANGED: 'PARENT_PHONE_CHANGED',
  PARENT_EMAIL_CHANGED: 'PARENT_EMAIL_CHANGED',
  PARENT_CHILD_UNLINKED: 'PARENT_CHILD_UNLINKED',
  PARENT_CARD_RENEWAL_REQUESTED: 'PARENT_CARD_RENEWAL_REQUESTED',

  // ── Broadcast ─────────────────────────────────────────────────────────────
  FESTIVAL_WISH_BROADCAST: 'FESTIVAL_WISH_BROADCAST',
  GOVT_ALERT_BROADCAST: 'GOVT_ALERT_BROADCAST',
  SERVER_MAINTENANCE: 'SERVER_MAINTENANCE',

  // ── Internal (coreZ team alerts) ─────────────────────────────────────────
  INTERNAL_ALERT: 'INTERNAL_ALERT',

  // ── System / Worker ───────────────────────────────────────────────────────
  WORKER_JOB_FAILED: 'WORKER_JOB_FAILED',
  WORKER_JOB_DEAD: 'WORKER_JOB_DEAD',
  WORKER_JOB_STALLED: 'WORKER_JOB_STALLED',
  SYSTEM_HEALTH_DEGRADED: 'SYSTEM_HEALTH_DEGRADED',
});

// ACTOR TYPES

export const ACTOR_TYPES = Object.freeze([
  'SUPER_ADMIN',
  'SCHOOL_ADMIN',
  'TEACHER',
  'PARENT',
  'PARENT_USER',
  'USER',
  'EMERGENCY_RESPONDER',
  'ATTENDANCE_DEVICE',
  'SYSTEM',
  'WORKER',
  'CRON',
]);

// EVENT GROUPS (for filtering/monitoring)

export const EVENT_GROUPS = {
  EMERGENCY: [
    EVENTS.EMERGENCY_ALERT_TRIGGERED,
    EVENTS.EMERGENCY_ALERT_DELIVERED,
    EVENTS.EMERGENCY_ALERT_FAILED,
    EVENTS.EMERGENCY_ALERT_ESCALATED,
  ],
  CRISIS: [
    EVENTS.CRISIS_TRIGGERED,
    EVENTS.CRISIS_RESOLVED,
    EVENTS.CRISIS_FAILED,
    EVENTS.TEACHER_ABSENT_DETECTED,
    EVENTS.ROOM_UNAVAILABLE_DETECTED,
    EVENTS.SUBSTITUTION_CREATED,
    EVENTS.SUBSTITUTION_APPROVED,
    EVENTS.SUBSTITUTION_REJECTED,
    EVENTS.MASS_LEAVE_DETECTED,
    EVENTS.WEATHER_EVENT_DETECTED,
  ],
  TIMETABLE: [
    EVENTS.TIMETABLE_GENERATE_STARTED,
    EVENTS.TIMETABLE_GENERATE_PROGRESS,
    EVENTS.TIMETABLE_GENERATE_COMPLETED,
    EVENTS.TIMETABLE_GENERATE_FAILED,
    EVENTS.TIMETABLE_GENERATE_CANCELLED,
    EVENTS.TIMETABLE_VALIDATE_STARTED,
    EVENTS.TIMETABLE_VALIDATE_COMPLETED,
    EVENTS.TIMETABLE_VALIDATE_FAILED,
    EVENTS.TIMETABLE_SWAP_REQUESTED,
    EVENTS.TIMETABLE_SWAP_COMPLETED,
    EVENTS.TIMETABLE_SWAP_FAILED,
    EVENTS.BULK_UPLOAD_STARTED,
    EVENTS.BULK_UPLOAD_PROGRESS,
    EVENTS.BULK_UPLOAD_COMPLETED,
    EVENTS.BULK_UPLOAD_FAILED,
  ],
  WELLNESS: [
    EVENTS.TEACHER_WELLNESS_UPDATED,
    EVENTS.TEACHER_BURNOUT_RISK_DETECTED,
    EVENTS.TEACHER_ACCESSIBILITY_VIOLATION,
    EVENTS.TEACHER_LOAD_WARNING,
  ],
  NOTIFICATION: [
    EVENTS.NOTIFICATION_SENT,
    EVENTS.NOTIFICATION_DELIVERED,
    EVENTS.NOTIFICATION_FAILED,
    EVENTS.NOTIFICATION_READ,
  ],
  STUDENT: [
    EVENTS.STUDENT_REGISTERED,
    EVENTS.STUDENT_QR_SCANNED,
    EVENTS.STUDENT_CARD_ACTIVATED,
    EVENTS.STUDENT_CARD_DEACTIVATED,
    EVENTS.ANOMALY_DETECTED,
  ],
  SYSTEM: [
    EVENTS.WORKER_JOB_FAILED,
    EVENTS.WORKER_JOB_DEAD,
    EVENTS.WORKER_JOB_STALLED,
    EVENTS.SYSTEM_HEALTH_DEGRADED,
  ],
};
