// =============================================================================
// orchestrator/events/event.types.js — RESQID
// =============================================================================

export const EVENTS = Object.freeze({
  // ── Emergency ────────────────────────────────────────────────────────────
  EMERGENCY_ALERT_TRIGGERED: 'EMERGENCY_ALERT_TRIGGERED',
  EMERGENCY_ALERT_DELIVERED: 'EMERGENCY_ALERT_DELIVERED',
  EMERGENCY_ALERT_FAILED: 'EMERGENCY_ALERT_FAILED',
  EMERGENCY_ALERT_ESCALATED: 'EMERGENCY_ALERT_ESCALATED',

  // ── Order lifecycle ───────────────────────────────────────────────────────
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_ADVANCE_INVOICE_ISSUED: 'ORDER_ADVANCE_INVOICE_ISSUED',
  PARTIAL_INVOICE_GENERATED: 'PARTIAL_INVOICE_GENERATED',
  ORDER_ADVANCE_PAYMENT_RECEIVED: 'ORDER_ADVANCE_PAYMENT_RECEIVED',
  PARTIAL_PAYMENT_CONFIRMED: 'PARTIAL_PAYMENT_CONFIRMED',
  ORDER_TOKEN_GENERATION_STARTED: 'ORDER_TOKEN_GENERATION_STARTED',
  ORDER_TOKEN_GENERATION_COMPLETE: 'ORDER_TOKEN_GENERATION_COMPLETE',
  ORDER_CARD_DESIGN_STARTED: 'ORDER_CARD_DESIGN_STARTED',
  ORDER_CARD_DESIGN_COMPLETE: 'ORDER_CARD_DESIGN_COMPLETE',
  ORDER_PDF_GENERATED: 'ORDER_PDF_GENERATED',
  ORDER_SENT_TO_VENDOR: 'ORDER_SENT_TO_VENDOR',
  ORDER_PRINTING_STARTED: 'ORDER_PRINTING_STARTED',
  ORDER_PRINTING_COMPLETE: 'ORDER_PRINTING_COMPLETE',
  ORDER_READY_TO_SHIP: 'ORDER_READY_TO_SHIP',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_BALANCE_INVOICE_ISSUED: 'ORDER_BALANCE_INVOICE_ISSUED',
  ORDER_BALANCE_PAYMENT_RECEIVED: 'ORDER_BALANCE_PAYMENT_RECEIVED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',
  ORDER_ON_HOLD: 'ORDER_ON_HOLD',
  DESIGN_APPROVED: 'DESIGN_APPROVED',

  // ── Auth / User ───────────────────────────────────────────────────────────
  USER_OTP_REQUESTED: 'USER_OTP_REQUESTED',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_DEVICE_LOGIN_NEW: 'USER_DEVICE_LOGIN_NEW',
  USER_PASSWORD_RESET_REQUESTED: 'USER_PASSWORD_RESET_REQUESTED',
  SCHOOL_USER_PASSWORD_RESET: 'SCHOOL_USER_PASSWORD_RESET',

  // ── School ────────────────────────────────────────────────────────────────
  SCHOOL_ONBOARDED: 'SCHOOL_ONBOARDED',
  SCHOOL_USER_ONBOARDED: 'SCHOOL_USER_ONBOARDED',
  SCHOOL_RENEWAL_DUE: 'SCHOOL_RENEWAL_DUE',
  SCHOOL_RENEWAL_COMPLETED: 'SCHOOL_RENEWAL_COMPLETED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',

  // ── Student ───────────────────────────────────────────────────────────────
  STUDENT_REGISTERED: 'STUDENT_REGISTERED',
  STUDENT_QR_SCANNED: 'STUDENT_QR_SCANNED',
  STUDENT_CARD_ACTIVATED: 'STUDENT_CARD_ACTIVATED',
  STUDENT_CARD_DEACTIVATED: 'STUDENT_CARD_DEACTIVATED',
  STUDENT_CARD_EXPIRING: 'STUDENT_CARD_EXPIRING',
  ANOMALY_DETECTED: 'ANOMALY_DETECTED',
  PROFILE_SETUP_REMINDER: 'PROFILE_SETUP_REMINDER',

  // ── Parent ────────────────────────────────────────────────────────────────
  PARENT_EMAIL_VERIFIED: 'PARENT_EMAIL_VERIFIED',
  PARENT_REGISTERED: 'PARENT_REGISTERED',
  PARENT_CARD_LINKED: 'PARENT_CARD_LINKED',
  PARENT_CARD_LOCKED: 'PARENT_CARD_LOCKED',
  PARENT_CARD_REPLACE_REQUESTED: 'PARENT_CARD_REPLACE_REQUESTED',
  PARENT_ACCOUNT_DELETED: 'PARENT_ACCOUNT_DELETED',
  PARENT_PHONE_CHANGED: 'PARENT_PHONE_CHANGED',
  PARENT_EMAIL_CHANGED: 'PARENT_EMAIL_CHANGED',
  PARENT_CHILD_UNLINKED: 'PARENT_CHILD_UNLINKED',
  PARENT_CARD_RENEWAL_REQUESTED: 'PARENT_CARD_RENEWAL_REQUESTED',

  // ── Broadcast ─────────────────────────────────────────────────────────────
  FESTIVAL_WISH_BROADCAST: 'FESTIVAL_WISH_BROADCAST',
  GOVT_ALERT_BROADCAST: 'GOVT_ALERT_BROADCAST',
  SERVER_MAINTENANCE: 'SERVER_MAINTENANCE',

  // ── Internal (coreZ team alerts) ─────────────────────────────────────────
  INTERNAL_ALERT: 'INTERNAL_ALERT',

  // ── System ────────────────────────────────────────────────────────────────
  WORKER_JOB_FAILED: 'WORKER_JOB_FAILED',
  WORKER_JOB_DEAD: 'WORKER_JOB_DEAD',
  SYSTEM_HEALTH_DEGRADED: 'SYSTEM_HEALTH_DEGRADED',
});

// ── Actor types ───────────────────────────────────────────────────────────────
export const ACTOR_TYPES = Object.freeze([
  'SUPER_ADMIN',
  'SCHOOL_ADMIN',
  'TEACHER',
  'PARENT',
  'EMERGENCY_RESPONDER',
  'ATTENDANCE_DEVICE',
  'SYSTEM',
  'WORKER',
]);
